// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCszjA16qyCNSLp3fEGWZnaNzlCsRJ_G_8',
    appId: '1:731816265740:web:1dbbc849bf58dfbb360629',
    messagingSenderId: '731816265740',
    projectId: 'smart-53431',
    authDomain: 'smart-53431.firebaseapp.com',
    storageBucket: 'smart-53431.firebasestorage.app',
    measurementId: 'G-NY1WL0TJF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYOnrJX8U8CSHZoZ4kJX6fc06NvsQs3aA',
    appId: '1:731816265740:android:93554a6cbcb8f60b360629',
    messagingSenderId: '731816265740',
    projectId: 'smart-53431',
    storageBucket: 'smart-53431.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsJOLsjv_2cToY2gox7UN1QM4magvp0tg',
    appId: '1:731816265740:ios:bf8e6ff60411f354360629',
    messagingSenderId: '731816265740',
    projectId: 'smart-53431',
    storageBucket: 'smart-53431.firebasestorage.app',
    iosBundleId: 'com.example.smartDustbin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsJOLsjv_2cToY2gox7UN1QM4magvp0tg',
    appId: '1:731816265740:ios:bf8e6ff60411f354360629',
    messagingSenderId: '731816265740',
    projectId: 'smart-53431',
    storageBucket: 'smart-53431.firebasestorage.app',
    iosBundleId: 'com.example.smartDustbin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCszjA16qyCNSLp3fEGWZnaNzlCsRJ_G_8',
    appId: '1:731816265740:web:ff4a47d676cc7652360629',
    messagingSenderId: '731816265740',
    projectId: 'smart-53431',
    authDomain: 'smart-53431.firebaseapp.com',
    storageBucket: 'smart-53431.firebasestorage.app',
    measurementId: 'G-JCHVJKJJEH',
  );

}